"""Version metadata used by both the scripts and the notebook."""

VERSIONS = {
    1: {
        "year": 2016,
        "title": "YOLOv1",
        "innovation": "画像全体を1回のCNNで処理し、グリッドごとにbboxとクラスを同時回帰",
        "use_case": "高速性が重要な動画・ロボットで、単段検出をリアルタイム利用",
        "demo": "grid",
        "paper": "https://arxiv.org/abs/1506.02640",
        "repo": "https://github.com/pjreddie/darknet",
        "backend": "darknet",
    },
    2: {
        "year": 2017,
        "title": "YOLOv2 / YOLO9000",
        "innovation": "anchor box、k-meansによるbox事前分布、BN、passthrough、階層分類",
        "use_case": "形状の異なる物体と多数カテゴリ（検出・分類データの共同学習）",
        "demo": "anchors",
        "paper": "https://arxiv.org/abs/1612.08242",
        "repo": "https://github.com/pjreddie/darknet",
        "backend": "darknet",
    },
    3: {
        "year": 2018,
        "title": "YOLOv3",
        "innovation": "Darknet-53、3スケール予測、FPN的な特徴融合、独立ロジスティック分類",
        "use_case": "小物体を含む監視映像や交通映像など、サイズ差の大きい対象",
        "demo": "multiscale",
        "paper": "https://arxiv.org/abs/1804.02767",
        "repo": "https://github.com/pjreddie/darknet",
        "backend": "darknet",
    },
    4: {
        "year": 2020,
        "title": "YOLOv4",
        "innovation": "CSPDarknet53、SPP+PAN、Mish、CIoU、Mosaic等のBoF/BoSを統合",
        "use_case": "単一GPUで学習しつつ高精度な産業・交通向けリアルタイム検出",
        "demo": "mosaic",
        "paper": "https://arxiv.org/abs/2004.10934",
        "repo": "https://github.com/AlexeyAB/darknet",
        "backend": "darknet",
    },
    5: {
        "year": 2020,
        "title": "YOLOv5",
        "innovation": "PyTorch実装、CSP系backbone、PAN-FPN、AutoAnchor、使いやすい学習・配備API",
        "use_case": "独自データの迅速な学習、ONNX/TensorRT等への実務配備",
        "demo": "focus",
        "paper": None,
        "repo": "https://github.com/ultralytics/yolov5",
        "backend": "ultralytics",
    },

    "yolox": {
        "year": 2021,
        "title": "YOLOX",
        "innovation": "anchor-free head、decoupled head、Simplified Optimal Transport Assignment (SimOTA)",
        "use_case": "YOLOv3系の検出器をanchor-freeと動的割当で近代化した比較対象",
        "demo": "anchor_free",
        "paper": "https://arxiv.org/abs/2107.08430",
        "repo": "https://github.com/Megvii-BaseDetection/YOLOX",
        "backend": "external",
    },
    6: {
        "year": 2022,
        "title": "YOLOv6",
        "innovation": "RepVGG系の再パラメータ化、TAL系割当、産業配備向け効率設計",
        "use_case": "物流・製造などGPU推論の低遅延が要求される産業用途",
        "demo": "reparam",
        "paper": "https://arxiv.org/abs/2209.02976",
        "repo": "https://github.com/meituan/YOLOv6",
        "backend": "external",
    },
    7: {
        "year": 2022,
        "title": "YOLOv7",
        "innovation": "E-ELAN、モデルscaling、予定再パラメータ化、trainable bag-of-freebies",
        "use_case": "エッジからGPUサーバまで、速度と精度の異なる制約へスケール",
        "demo": "elan",
        "paper": "https://arxiv.org/abs/2207.02696",
        "repo": "https://github.com/WongKinYiu/yolov7",
        "backend": "external",
    },
    8: {
        "year": 2023,
        "title": "YOLOv8",
        "innovation": "anchor-free decoupled head、C2f、タスク統合API（検出・分割・姿勢等）",
        "use_case": "同じ操作体系で検出、segmentation、pose、trackingを試す製品開発",
        "demo": "anchor_free",
        "paper": None,
        "repo": "https://github.com/ultralytics/ultralytics",
        "backend": "ultralytics",
    },

    "yolo-nas": {
        "year": 2023,
        "title": "YOLO-NAS",
        "innovation": "Neural Architecture Searchにより速度・精度・配備性のバランスを探索",
        "use_case": "SuperGradients等の実装で、探索済みモデルを実用配備の比較対象にする",
        "demo": "nas",
        "paper": None,
        "repo": "https://github.com/Deci-AI/super-gradients",
        "backend": "external",
    },
    "rt-detr": {
        "year": 2023,
        "title": "RT-DETR",
        "innovation": "DETR系のquery-based / end-to-end / NMS-free検出をリアルタイム化",
        "use_case": "YOLO系dense detectorとNMS-free Transformer detectorを同条件で比較",
        "demo": "query",
        "paper": "https://arxiv.org/abs/2304.08069",
        "repo": "https://github.com/lyuwenyu/RT-DETR",
        "backend": "external",
    },
    9: {
        "year": 2024,
        "title": "YOLOv9",
        "innovation": "Programmable Gradient Information (PGI) と GELAN",
        "use_case": "軽量モデルでも学習時の情報損失を抑えたいエッジ検出",
        "demo": "pgi",
        "paper": "https://arxiv.org/abs/2402.13616",
        "repo": "https://github.com/WongKinYiu/yolov9",
        "backend": "ultralytics",
    },
    10: {
        "year": 2024,
        "title": "YOLOv10",
        "innovation": "consistent dual assignmentsによるend-to-end NMS-free検出と効率設計",
        "use_case": "NMS遅延を避けたいストリーミング・組込みリアルタイム推論",
        "demo": "nms_free",
        "paper": "https://arxiv.org/abs/2405.14458",
        "repo": "https://github.com/THU-MIG/yolov10",
        "backend": "ultralytics",
    },
    11: {
        "year": 2024,
        "title": "YOLO11",
        "innovation": "C3k2/C2PSA等で特徴抽出とattentionを効率化しマルチタスク性能を改善",
        "use_case": "限られた計算資源で検出・分割・姿勢・OBB・分類を横断利用",
        "demo": "attention",
        "paper": None,
        "repo": "https://github.com/ultralytics/ultralytics",
        "backend": "ultralytics",
    },
    12: {
        "year": 2025,
        "title": "YOLOv12",
        "innovation": "Area Attention (A2) と R-ELANでattentionをリアルタイム検出向けに最適化",
        "use_case": "混雑場面など広い文脈が必要で、CNN並みの低遅延も必要な検出",
        "demo": "area_attention",
        "paper": "https://arxiv.org/abs/2502.12524",
        "repo": "https://github.com/sunsmarterjie/yolov12",
        "backend": "ultralytics",
    },
    13: {
        "year": 2025,
        "title": "YOLOv13",
        "innovation": "HyperACEによるhypergraph特徴相関、FullPAD、DS-based label assignment",
        "use_case": "遮蔽・密集・離れた部位の関係など高次の特徴相関が重要な場面",
        "demo": "hypergraph",
        "paper": "https://arxiv.org/abs/2506.17733",
        "repo": "https://github.com/iMoonLab/yolov13",
        "backend": "external",
    },
    26: {
        "year": 2026,
        "title": "YOLO26 (Ultralytics product line)",
        "innovation": "end-to-end NMS-free推論、DFL除去、ProgLoss+STAL、MuSGDによる学習最適化",
        "use_case": "CPU・エッジ機器への配備と、後処理を単純化した低遅延end-to-end推論",
        "demo": "deployment",
        "paper": None,
        "repo": "https://github.com/ultralytics/ultralytics",
        "docs": "https://docs.ultralytics.com/models/yolo26/",
        "backend": "ultralytics",
    },
}
